### ISSUE TITLE
Change size

### ISSUE THREAD

**Issue by JonnyDillon** [stevenschobert/instafeed.js#239]
I want the highest resolution possible so have selected standard resolution but i would like to control the size of the images using CSS? is this possible?

**Comment by stevenschobert** [comment]
Yes! The exact CSS selector you use depends on what you have in your template, but this works for the default settings:

```css
#instafeed img {
  width: 500px;
  height: 500px;
}
```
